apiVersion: v1
kind: Pod
metadata:
  name: postgrespod
  labels: 
    app: myapp
spec:
  restartPolicy: Never
  containers:
  - name: myappcontainer
    image: postgres
    imagePullPolicy: Always
    env:
    - name: POSTGRES_PASSWORD
      value: "root"
    ports: 
    - containerPort: 5432