apiVersion: v1
kind: Pod
metadata:
  name: rabbitmqpod
  labels: 
    app: myapp
spec:
  restartPolicy: Never
  containers:
  - name: myappcontainer
    image: rabbitmq
    imagePullPolicy: Always
    env:
    - name: RABBITMQ_DEFAULT_USER
      value: "root"
    - name: RABBITMQ_DEFAULT_PASS
      value: "root"
    ports: 
    - containerPort: 5672